---
title: "Cleaning"
execute:
  message: false
  warning: false
---

## Clean it up

```{r}
library(tidyverse)
library(janitor)
library(here)

global_catch <- read_csv(here("data", # data is in the "data" folder in this repository
                         "global-fishery-catch-by-sector.csv")) # file name
```


```{r}
global_catch %>% 
  # new function: clean_names
  # makes the column names nicer! compare this with the column names from `colnames(global_catch)` output from above
  clean_names()
```

```{r}
global_catch %>% 
  clean_names() %>% # same as above

  # new function: mutate
  # create new columns to calculate catch divided by 1000000
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000)
```

```{r}
global_catch %>% 
  clean_names() %>% 
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000) %>% # same as above
  
  # new function: select
  # select the columns you're interested in 
  select(year, artisanal, industrial)
```

```{r}
global_catch %>% 
  clean_names() %>% 
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000) %>% 
  select(year, artisanal, industrial) %>% # same as above
  
  # new function: pivot_longer
  # put the data frame in long format: each row is an observation
  # in this case, each row is a fishery with some catch (in million tons) in a given year
  pivot_longer(cols = artisanal:industrial)
```

```{r}
global_catch %>% 
  clean_names() %>% 
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000) %>% 
  select(year, artisanal, industrial) %>% 
  pivot_longer(cols = artisanal:industrial) %>% # same as above
  
  # new function: rename
  # renames columns so that they are easier to understand
  # arguments: "new name" = "old name"
  rename(catch_mil = value,
         fishery_type = name) 
```

```{r}
global_catch %>% 
  clean_names() %>% 
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000) %>% 
  select(year, artisanal, industrial) %>% 
  pivot_longer(cols = artisanal:industrial) %>% 
  rename(catch_mil = value,
         fishery_type = name) %>% # same as above
  
  # new function: mutate with case_when
  # creates new column of full names for fisheries
  mutate(fishery_full_name = case_when(
    fishery_type == "artisanal" ~ "Artisanal fishery",
    fishery_type == "industrial" ~ "Industrial fishery"
  ))
```

```{r}
global_catch %>% 
  clean_names() %>% 
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000) %>% 
  select(year, artisanal, industrial) %>% 
  pivot_longer(cols = artisanal:industrial) %>% 
  rename(catch_mil = value,
         fishery_type = name) %>% 
  mutate(fishery_full_name = case_when(
    fishery_type == "artisanal" ~ "Artisanal fishery",
    fishery_type == "industrial" ~ "Industrial fishery"
  )) %>% # same as above
  
  # new function: filter
  # filters data frame for observations after 1980
  filter(year > 1980)
```

All together to create a data frame called `global_catch_clean`

```{r}
global_catch_clean <- global_catch %>% 
  
  # makes the column names nicer
  clean_names() %>% 
  
  # divides catch by 1000000 to calculate catch in million tons
  mutate(artisanal = artisanal_small_scale_commercial/1000000,
         industrial = industrial_large_scale_commercial/1000000) %>% 
  
  # selecting columns
  select(year, artisanal, industrial) %>% 
  
  # put the data frame in long format: each row is an observation
  pivot_longer(cols = artisanal:industrial) %>% 
  
  # renames columns so that they are easier to understand
  rename(catch_mil = value,
         fishery_type = name) %>% 
  
  # creates new column of full names for fisheries
  mutate(fishery_full_name = case_when(
    fishery_type == "artisanal" ~ "Artisanal fishery",
    fishery_type == "industrial" ~ "Industrial fishery"
  )) %>% 
  
  # filters data frame for observations after 1980
  filter(year > 1980)
```
