project:
  type: book
  output-dir: docs

book:
  title: "EEMB Data Management Workshop"
  author: "An Bui"
  search: true
  repo-url: https://github.com/an-bui/eemb-data-management-workshop
  chapters:
    - index.qmd
    - 01_packages.qmd
    - 02_reading-your-data.qmd
    - 03_looking-at-your-data.qmd
    - 04_cleaning.qmd
    - 05_visualizing.qmd
    - 06_follow-ups.qmd
    - 07_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt
execute:
  message: false
  warning: false
  freeze: auto



